### ISSUE TITLE
 example_svm.py raise ImportError

### ISSUE THREAD

**Issue by CristianCantoro** [pybrain/pybrain#104]
In `pybrain/examples/supervised/neuralnets+svm`

```
$ python example_svm.py
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    from pybrain.supervised.trainers.svmtrainer   import SVMTrainer
  File "/home/cristian/.virtualenvs/apritilegge/local/lib/python2.7/site-packages/pybrain/supervised/trainers/svmtrainer.py", line 9, in <module>
    raise ImportError("Cannot find LIBSVM installation. Make sure svm.py and svmc.* are in the PYTHONPATH!")
ImportError: Cannot find LIBSVM installation. Make sure svm.py and svmc.* are in the PYTHONPATH!
```

The problem seems that now the function `cross_validation` is in `svm.svmlib.cross_validation` instead of `svm.cross_validation`, furthermore the structure of the `svm.py` module seems to have changed signficantly. For example, both the `svm_parameter` and `svm_model` have different constructors from what the `pybrain.supervised.trainers.svmtrainer.SVMTrainer` is assuming.

So this example does not work anymore.

**Comment by hansbonini** [comment]
I had the same error.

"cross_validation" doesnt exists in python bindings of libsvm latest release
