### ISSUE TITLE
Can't run tutorial

### ISSUE THREAD

**Issue by Tjorriemorrie** [pybrain/pybrain#123]
Error:

```
$ python rl.py
Traceback (most recent call last):
  File "rl.py", line 22, in <module>
    from pybrain.rl.environments.mazes import Maze, MDPMazeTask
ImportError: No module named pybrain.rl.environments.mazes
```

**Comment by tkelestemur** [comment]
I am still getting this error, running on MacOS 10.10

```
Traceback (most recent call last):
  File "td.py", line 13, in <module>
    from pybrain.rl.environments.mazes import Maze, MDPMazeTask
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyBrain-0.3.3-py2.7.egg/pybrain/rl/environments/mazes/__init__.py", line 3, in <module>
    from pybrain.rl.environments.mazes.tasks.__init__ import *
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyBrain-0.3.3-py2.7.egg/pybrain/rl/environments/mazes/tasks/__init__.py", line 1, in <module>
    from pybrain.rl.environments.mazes.tiger import TigerTask
ImportError: No module named tiger
```

**Comment by SBretz** [comment]
Hi tkelestermur. The above fix should have solved this issue but it seems it was never merged. I'll submit another pull request.

If you are in a hurry you can fix this issue on your machine by editing 
pybrain/rl/environments/mazes/tasks/__init_.py to look like this:

from pybrain.rl.environments.mazes.tasks.tiger import TigerTask
from pybrain.rl.environments.mazes.tasks.maze import TrivialMaze, MazeTask
from pybrain.rl.environments.mazes.tasks.cheesemaze import CheeseMaze
from pybrain.rl.environments.mazes.tasks.tmaze import TMaze
from pybrain.rl.environments.mazes.tasks.maze4x3 import FourByThreeMaze
from pybrain.rl.environments.mazes.tasks.maze89state import EightyNineStateMaze
from pybrain.rl.environments.mazes.tasks.shuttle import ShuttleDocking
from pybrain.rl.environments.mazes.tasks.mdp import MDPMazeTask

and then reinstall pybrain using setup.py.

**Comment by tkelestemur** [comment]
Hi SBretz, thanks for the fix. I am now able to run it without any error.

**Comment by hobson** [comment]
PR [#157](https://github.com/pybrain/pybrain/pull/157) will fix this.
