### ISSUE TITLE
[RL] Error on __init__.py of pybrain.rl.environments.mazes.tasks

### ISSUE THREAD

**Issue by goramos** [pybrain/pybrain#133]
The **init**.py file of pybrain.rl.environments.mazes.tasks has wrong imports. While importing pybrain.rl.environments.mazes, the following error is generated:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/rl/environments/mazes/**init**.py", line 3, in <module>
    from pybrain.rl.environments.mazes.tasks.**init** import *
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/rl/environments/mazes/tasks/**init**.py", line 2, in <module>
    from pybrain.rl.environments.mazes.tiger import TigerTask
ImportError: No module named tiger

I have changed **init**.py in my machine. In each of its 8 lines, I have included tasks after mazes. The resulting file is:
from pybrain.rl.environments.mazes.tasks.tiger import TigerTask
from pybrain.rl.environments.mazes.tasks.maze import TrivialMaze, MazeTask
from pybrain.rl.environments.mazes.tasks.cheesemaze import CheeseMaze
from pybrain.rl.environments.mazes.tasks.tmaze import TMaze
from pybrain.rl.environments.mazes.tasks.maze4x3 import FourByThreeMaze
from pybrain.rl.environments.mazes.tasks.maze89state import EightyNineStateMaze
from pybrain.rl.environments.mazes.tasks.shuttle import ShuttleDocking
from pybrain.rl.environments.mazes.tasks.mdp import MDPMazeTask

After that, the error does not happen anymore.
Can someone fix this in the PyBrain repository?

Thanks,
Gabriel

**Comment by hobson** [comment]
PR [#157](https://github.com/pybrain/pybrain/pull/157) will fix this.
