### ISSUE TITLE
Failed at examples/optimization/multiobjective/nsga2.py

### ISSUE THREAD

**Issue by akakcolin** [pybrain/pybrain#142]
I got a TypeError: object of type 'int' has no len()
more detail:
Traceback (most recent call last):
  File "nsga2.py", line 19, in <module>
    n = MultiObjectiveGA(f, x0, storeAllEvaluations = True)
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/optimization/optimizer.py", line 93, in **init**
    self.setEvaluator(evaluator, initEvaluable)  
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/optimization/optimizer.py", line 155, in setEvaluator
    self._additionalInit()
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/optimization/populationbased/evolution.py", line 20, in _additionalInit
    self.initPopulation()
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/optimization/populationbased/ga.py", line 44, in initPopulation
    self.initBoundaries()
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.1-py2.7.egg/pybrain/optimization/populationbased/ga.py", line 37, in initBoundaries
    assert len(self.xBound) == self.numParameters
TypeError: object of type 'int' has no len()

**Comment by sah4ez** [comment]
HI,
are you fixed this problem?
