### ISSUE TITLE
AssertionError: (1, 36)

### ISSUE THREAD

**Issue by JustVic** [pybrain/pybrain#194]
Writing reinforcement learning bot almost like in example http://pybrain.org/docs/tutorial/reinforcement-learning.html, but can't getting it work. And always get this error

Traceback (most recent call last):
  File "./bot3.py", line 95, in <module>
    run_bbox(verbose=0)
  File "./bot3.py", line 87, in run_bbox
    experiment.doInteractions(100000)
  File "/usr/local/lib/python2.7/dist-packages/pybrain/rl/experiments/experiment.py", line 18, in doInteractions
    self._oneInteraction()
  File "/usr/local/lib/python2.7/dist-packages/pybrain/rl/experiments/experiment.py", line 27, in _oneInteraction
    self.task.performAction(self.agent.getAction())
  File "/usr/local/lib/python2.7/dist-packages/pybrain/rl/agents/learning.py", line 50, in getAction
    self.lastaction = self.module.activate(self.lastobs)
  File "/usr/local/lib/python2.7/dist-packages/pybrain/structure/modules/module.py", line 104 in activate
    assert len(self.inputbuffer[self.offset]) == len(inpt), str((len(self.inputbuffer[self.offset]), len(inpt))) 
AssertionError: (1, 36)

Why len(self.inputbuffer[self.offset]) always 1?
My env.getSensors() method returns numply array of 36 doubles, I have 4 actions.

**Comment by antoine9298** [comment]
I got the same problem, and when I silent the assert by editing pybrain’s source, i get this :
```
ValueError: could not broadcast input array from shape (14) into shape (1)
```

So I think our input is wrong.

But HOW to get it right, then ? (we really need a *good* documentation)

**Comment by fredrikomstedt** [comment]
Any updates on this? My table is initialized as this:
```
action_value_table = ActionValueTable(350, 2)
```
But these 350 states are divided over four different dimensions, as can be shown here:
```
#In my derived Environment
def getSensors(self):
        obs = zeros(4)
        obs[0] = float(self.delay_ns)
        obs[1] = float(self.delay_we)
        obs[2] = float(self.phase_time)
        obs[3] = float(self.west_east)
        return obs
```

Am I doing something wrong or is there something wrong with the code? Does anybody know how to fix it? When running the tutorial as mentioned above, everything works perfectly fine so I don't understand what I am doing wrong.
