### ISSUE TITLE
ImportError: No module named 'structure' (python3)

### ISSUE THREAD

**Issue by demidovakatya** [pybrain/pybrain#201]
Hi,

1\. When I try to install Pybrain on Python 3, I see this error:

```
pip install pybrain
> ImportError: No module named 'structure'
```

2\. Okay then, we need `structure`, let's get it:

```
pip install structure
```

![](https://cloud.githubusercontent.com/assets/5788652/15796322/0dfeba06-2a0d-11e6-9075-c1733f964bc0.png)

3\. After many trials and errors, this command helped:

```
sudo python3.5 setup.py install
```

And there are some questions: 

* Is this a bug or a feature?  (Just curious: _why_ this happened?)
* Except for this problem with installation, is Pybrain python3-friendly?
* Is installation via `sudo python3.5 setup.py install` the best way to avoid that `ImportError`?

**Comment by chrisspen** [comment]
I'm also getting these errors in the current release, which doesn't appear to support Python3. However, these all appear to have been fixed in master **two years ago**. When will these fixes be released?

**Comment by MaevaLC** [comment]
Sorry to up this again, but I have the same error message. 
I installed it with pip, successful and everything. But now I'm just trying to import it and nope, "ImportError: No module named 'structure'". I'm using Python 3.5, with Spyder 2.3.9.
Did you manage to find a solution ?

**Comment by iamtodor** [comment]
@MaevaLC try this: `pip install https://github.com/pybrain/pybrain/archive/0.3.3.zip`.
For those folks, who get message error: `-bash: pip: command not found` try the following command:`pip3 install https://github.com/pybrain/pybrain/archive/0.3.3.zip`

**Comment by MaevaLC** [comment]
Installation is successful, thank you !

**Comment by Jiyya** [comment]
@iamtodor  kindly solve my problem as well
from patch_library import PatchLibrary
ModuleNotFoundError: No module named 'patch_library'
thanks in advance

**Comment by GrininViktor** [comment]
Thank you, very much!

**Comment by miltondsantos** [comment]
Hi Dears,

One more thing about the import error, in special, with expm2. My action as follows:

1) I got this error running this "from pybrain.structure import FeedForwardNetwork"
Error:

  File "/home/milton/anaconda2/envs/py36/lib/python3.5/site-packages/pybrain/tools/functions.py", **line 4**, in <module>
    from scipy.linalg import inv, det, svd, logm, expm2

ImportError: cannot import name 'expm2'

2) I checked that scipy intermit expm2 on version since v. 0.17
3) I uninstall the scipy via conda;
3) I installed the pip3
4) I Installed the scipy via pip3

I changed that:
**from scipy.linalg import inv, det, svd, logm, expm2**

for this:
**from scipy.linalg import inv, det, svd, logm, expm**

Regards
Milton

**Comment by mpriya-sv** [comment]
> Hi,
> 
> 1. When I try to install Pybrain on Python 3, I see this error:
> 
> ```
> pip install pybrain
> > ImportError: No module named 'structure'
> ```
> 
> 1. Okay then, we need `structure`, let's get it:
> 
> ```
> pip install structure
> ```
> 
> ![](https://cloud.githubusercontent.com/assets/5788652/15796322/0dfeba06-2a0d-11e6-9075-c1733f964bc0.png)



Thank you so much. This helped me !

**Comment by MarquisAlexander** [comment]
> Ola queridos,
> 
> Mais uma coisa sobre o erro de importação, em especial, com expm2. Minha ação da seguinte maneira:
> 
> 1. Eu recebi este erro executando este erro "from pybrain.structure import FeedForwardNetwork" 
>    :
> 
> Arquivo "/home/milton/anaconda2/envs/py36/lib/python3.5/site-packages/pybrain/tools/functions.py", **linha 4** ,
> do scipy.linalg import inv, det, svd, logm, expm2
> 
> ImportError: não é possível importar o nome 'expm2'
> 
> 1. Eu verifiquei que scipy intermitiu expm2 na versão desde a versão 0,17
> 2. Eu desinstalo o scipy via conda;
> 3. Eu instalei o pip3
> 4. Eu instalei o scipy via pip3
> 
> Eu mudei isso:
> **de scipy.linalg import inv, det, svd, logm, expm2**
> 
> para isso:
> **de scipy.linalg import inv, det, svd, logm, expm**
> 
> Atenciosamente
> Milton

thanks, great here!

**Comment by commander-cb** [comment]
yeah .
and not having structure as a dependenxy is ....

**Comment by Ickwarw** [comment]
this error is being presented when I use this pybrain library

this is my code:
from pybrain.structure import FeedForwardNetwork
from pybrain.structure import LinearLayer, SigmoidLayer, BiasUnit
from pybrain.structure import FullConnection

rneural = FeedForwardNetwork()

CE = LinearLayer(4)
CO = SigmoidLayer(6)
CS = SigmoidLayer(1)
b1 = BiasUnit()
b2 = BiasUnit()

rneural.addModule(CE)
rneural.addModule(CO)
rneural.addModule(CS)
rneural.addModule(b1)
rneural.addModule(b2)

EO = FullConnection(CE, CO)
OS = FullConnection(CO, CS)
bO = FullConnection(b1, CO)
bS = FullConnection(b2, CS)

rneural.sortModule()
print(rneural)

when I run:

python3 rneural.py
Traceback (most recent call last):
  File "/home/warwick/Desktop/scriptsinpython/ai/rneural.py", line 1, in <module>
    from pybrain.structure import FeedForwardNetwork
  File "/home/warwick/environments/my_env/lib/python3.10/site-packages/pybrain/__init__.py", line 1, in <module>
    from pybrain.structure.__init__ import *
  File "/home/warwick/environments/my_env/lib/python3.10/site-packages/pybrain/structure/__init__.py", line 2, in <module>
    from pybrain.structure.modules.__init__ import *
  File "/home/warwick/environments/my_env/lib/python3.10/site-packages/pybrain/structure/modules/__init__.py", line 2, in <module>
    from pybrain.structure.modules.gate import GateLayer, DoubleGateLayer, MultiplicationLayer, SwitchLayer
  File "/home/warwick/environments/my_env/lib/python3.10/site-packages/pybrain/structure/modules/gate.py", line 10, in <module>
    from pybrain.tools.functions import sigmoid, sigmoidPrime
  File "/home/warwick/environments/my_env/lib/python3.10/site-packages/pybrain/tools/functions.py", line 4, in <module>
    from scipy.linalg import inv, det, svd, logm, expm2
ImportError: cannot import name 'expm2' from 'scipy.linalg' (/home/warwick/environments/my_env/lib/python3.10/site-packages/scipy/linalg/__init__.py)


I've tried several solutions but the only one I haven't tried is to downgrade python3.10, I think it's not the most correct solution if anyone knows how to fix this

thanks
