### ISSUE TITLE
assertionError: (4,2) when run cartpole example

### ISSUE THREAD

**Issue by FocusLiwen** [pybrain/pybrain#206]
Hi,

When I just run cartPole example, I got the following error message:

In [7]: runfile('H:/LearningRL/CartPole.py', wdir='H:/LearningRL')
<matplotlib.figure.Figure at 0x13c5d7b0>
Traceback (most recent call last):

  File "<ipython-input-7-7652090017a6>", line 1, in <module>
    runfile('H:/LearningRL/CartPole.py', wdir='H:/LearningRL')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "H:/LearningRL/CartPole.py", line 51, in <module>
    experiment.doEpisodes(1)

  File "C:\Python27\lib\site-packages\pybrain-0.3-py2.7.egg\pybrain\rl\experiments\episodic.py", line 42, in doEpisodes
    r = self._oneInteraction()

  File "C:\Python27\lib\site-packages\pybrain-0.3-py2.7.egg\pybrain\rl\experiments\episodic.py", line 27, in _oneInteraction
    return Experiment._oneInteraction(self)

  File "C:\Python27\lib\site-packages\pybrain-0.3-py2.7.egg\pybrain\rl\experiments\experiment.py", line 27, in _oneInteraction
    self.task.performAction(self.agent.getAction())

  File "C:\Python27\lib\site-packages\pybrain-0.3-py2.7.egg\pybrain\rl\agents\learning.py", line 50, in getAction
    self.lastaction = self.module.activate(self.lastobs)

  File "C:\Python27\lib\site-packages\pybrain-0.3-py2.7.egg\pybrain\structure\modules\module.py", line 104, in activate
    assert len(self.inputbuffer[self.offset]) == len(inpt), str((len(self.inputbuffer[self.offset]), len(inpt)))

AssertionError: (4, 2)

What is happening there? What is the self.inutbuffer[self.offset]?

**Comment by antoine9298** [comment]
Good question, I got the same problem, and it is quite frequent :
see the issue #194, last comment of #100, [this](http://stackoverflow.com/questions/35380853/i-cant-get-deepbelieftrainer-to-work-with-feedforwardnetwork-in-pybrain), [here](http://stackoverflow.com/questions/23441181/pybrain-reinforcement-learning-input-buffer-incorrect#27760306) (…)

So, is it a bug, or is it that we are going the wrong way ? If we are going the wrong way, it would be kind to make the documentation more clear, and more understandable, and to get a meaningful error, but, if it’s a bug, let’s fix it, and provide a better documentation anyway, since it **is** needed
