### ISSUE TITLE
Unit tests fail on macosx

### ISSUE THREAD

**Issue by amrsharaf** [pybrain/pybrain#214]
6 out of 31 unittests failed on Mac OS X. Most of the errors where either:

TypeError: slice indices must be integers or None or have an __index__ method

or in test_rprop, some array values were expected to be zero, but they didn't match the actual outputs.

**Comment by gormih** [comment]
On ubuntu as 6 mistakes.
It seems that one does not launch unit tests before publishing ...

**Comment by PrinceWale** [comment]
Sorry. I do not understand

**Comment by bieschke** [comment]
Same 6/31 unit test failures here on OSX off of a fresh install. Below is the full output:

Erics-iMac:tests eric$ python runtests.py 
INFO Tests found: pybrain.tests.unittests.auxiliary.test_pca
INFO Tests found: pybrain.tests.unittests.datasets.test_datasets_datasets
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/optimization
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/rl
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/structure
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/supervised
WARNING Module pybrain.tests.unittests.tools.test_rlgluebridge is missing dependencies: rlglue
INFO Tests found: pybrain.tests.unittests.tools.test_ibp_leftordered
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/unsupervised
INFO Tests found: pybrain.tests.unittests.optimization.populationbased.test_pso_ring
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/rl/environments
INFO Tests found: pybrain.tests.unittests.rl.environments.twoplayergames.test_capture_game
INFO Tests found: pybrain.tests.unittests.rl.environments.twoplayergames.test_pente
INFO Tests found: pybrain.tests.unittests.structure.connections.test_shared_connections
INFO Tests found: pybrain.tests.unittests.structure.connections.test_sliced_connections
INFO Tests found: pybrain.tests.unittests.structure.connections.test_subsampling_connection
INFO Tests found: pybrain.tests.unittests.structure.modules.test_peephole_lstm
INFO Tests found: pybrain.tests.unittests.structure.modules.test_peephole_mdlstm
INFO Tests found: pybrain.tests.unittests.structure.modules.test_samplelayer
INFO Tests found: pybrain.tests.unittests.structure.modules.test_simple_lstm_network
INFO Tests found: pybrain.tests.unittests.structure.modules.test_simple_mdlstm
INFO No fast networks available: No module named 'arac'
INFO Tests found: pybrain.tests.unittests.structure.networks.test_bidirectional_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_borderswipingnetwork
INFO Tests found: pybrain.tests.unittests.structure.networks.test_cyclic_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
INFO Tests found: pybrain.tests.unittests.structure.networks.test_nested_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_decomposition
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_forward_backward
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_sort
INFO Tests found: pybrain.tests.unittests.structure.networks.test_no_gravity_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_recurrent_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_swiping_network
INFO Tests found: pybrain.tests.unittests.structure.networks.custom.test_capturegame_network
INFO Tests found: pybrain.tests.unittests.structure.networks.custom.test_convolutional_nets
INFO No tests found in /Users/eric/dev/gloom3/pybrain/pybrain/tests/unittests/supervised/knn
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_backprop
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_evolino
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_rprop
INFO Tests found: pybrain.tests.unittests.supervised.knn.lsh.test_minhash
INFO Tests found: pybrain.tests.unittests.supervised.knn.lsh.test_nearoptimal
...........FF...F.....F....FF..
======================================================================
FAIL: test_simple_lstm_network (pybrain.tests.unittests.structure.modules)
Doctest: pybrain.tests.unittests.structure.modules.test_simple_lstm_network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.modules.test_simple_lstm_network
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 0, in test_simple_lstm_network

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 17, in pybrain.tests.unittests.structure.modules.test_simple_lstm_network
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_lstm_network[3]>", line 1, in <module>
        gradientCheck(n)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 27, in pybrain.tests.unittests.structure.modules.test_simple_lstm_network
Failed example:
    gradientCheck(net)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_lstm_network[10]>", line 1, in <module>
        gradientCheck(net)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method


======================================================================
FAIL: test_simple_mdlstm (pybrain.tests.unittests.structure.modules)
Doctest: pybrain.tests.unittests.structure.modules.test_simple_mdlstm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.modules.test_simple_mdlstm
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/modules/test_simple_mdlstm.py", line 0, in test_simple_mdlstm

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/modules/test_simple_mdlstm.py", line 17, in pybrain.tests.unittests.structure.modules.test_simple_mdlstm
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_mdlstm[3]>", line 1, in <module>
        gradientCheck(n)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method


======================================================================
FAIL: test_nested_ffn_and_rnn (pybrain.tests.unittests.structure.networks)
Doctest: pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/networks/test_nested_ffn_and_rnn.py", line 0, in test_nested_ffn_and_rnn

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/networks/test_nested_ffn_and_rnn.py", line 41, in pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn[14]>", line 1, in <module>
        gradientCheck(n)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method


======================================================================
FAIL: test_recurrent_network (pybrain.tests.unittests.structure.networks)
Doctest: pybrain.tests.unittests.structure.networks.test_recurrent_network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.networks.test_recurrent_network
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/networks/test_recurrent_network.py", line 0, in test_recurrent_network

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/structure/networks/test_recurrent_network.py", line 16, in pybrain.tests.unittests.structure.networks.test_recurrent_network
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.structure.networks.test_recurrent_network[3]>", line 1, in <module>
        gradientCheck(n)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method


======================================================================
FAIL: test_evolino (pybrain.tests.unittests.supervised.trainers)
Doctest: pybrain.tests.unittests.supervised.trainers.test_evolino
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.supervised.trainers.test_evolino
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 0, in test_evolino

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 33, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    trainer.trainEpochs( 1 )
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_evolino[9]>", line 1, in <module>
        trainer.trainEpochs( 1 )
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/evolino.py", line 131, in train
        filter.apply(self._population)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/evolino/filter.py", line 117, in apply
        fitness = self._evaluateNet(net, dataset, self.wtRatio)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/evolino/filter.py", line 59, in _evaluateNet
        sequence = dataset.getSequence(i)[1]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 34, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    trainer.evaluation.max_fitness > -100
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 38, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    net.extrapolate(sequence, len(sequence))[-1][0]>55
Expected:
    True
Got:
    False


======================================================================
FAIL: test_rprop (pybrain.tests.unittests.supervised.trainers)
Doctest: pybrain.tests.unittests.supervised.trainers.test_rprop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 2187, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.supervised.trainers.test_rprop
  File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 0, in test_rprop

----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 23, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    t.trainOnDataset(ds, 4)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_rprop[12]>", line 1, in <module>
        t.trainOnDataset(ds, 4)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/trainer.py", line 30, in trainOnDataset
        self.trainEpochs(*args, **kwargs)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/backprop.py", line 57, in train
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 28, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    abs(n.params[10:15] - array([ -0.53868206, -0.54185834,  0.26726394, -1.90008234, -1.12114946])).round(5)
Expected:
    array([ 0.,  0.,  0.,  0.,  0.])
Got:
    array([ 0.07526,  0.07613,  0.0253 ,  0.0132 ,  0.60377])
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 34, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    t.trainOnDataset(ds, 4)
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_rprop[15]>", line 1, in <module>
        t.trainOnDataset(ds, 4)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/trainer.py", line 30, in trainOnDataset
        self.trainEpochs(*args, **kwargs)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/supervised/trainers/rprop.py", line 43, in train
        for seq in self.ds._provideSequences():
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 56, in <listcomp>
        return [self._getSequenceField(index, l) for l in self.link]
      File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 39, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    abs(n.params[5:10] - array([ -0.19241111,  1.43404022,  0.23062397, -0.40105413,  0.62100109])).round(5)
Expected:
    array([ 0.,  0.,  0.,  0.,  0.])
Got:
    array([ 0.04173,  0.14517,  0.53681,  0.06842,  0.07844])


----------------------------------------------------------------------
Ran 31 tests in 4.957s

FAILED (failures=6)

**Comment by bieschke** [comment]
While I don't know PyBrain well enough to know if this patch is appropriate, but this patch fixes all of the unit tests on OSX:

```
Erics-iMac:tests eric$ diff !$ ../datasets/sequential.py 
diff /Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py ../datasets/sequential.py 
45c45
<             return self.getField(field)[int(seq[index]):]
---
>             return self.getField(field)[seq[index]:]
49c49
<         return self.getField(field)[int(seq[index]):int(seq[index + 1])]
---
>         return self.getField(field)[seq[index]:seq[index + 1]]
Erics-iMac:tests eric$ ^diff^diff -p^
diff -p /Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py ../datasets/sequential.py 
*** /Users/eric/.virtualenvs/gloom3/lib/python3.4/site-packages/PyBrain-0.3.3-py3.4.egg/pybrain/datasets/sequential.py	2017-09-04 13:44:40.000000000 -0700
--- ../datasets/sequential.py	2017-09-04 13:20:34.000000000 -0700
*************** class SequentialDataSet(SupervisedDataSe
*** 42,52 ****
          seq = ravel(self.getField('sequence_index'))
          if len(seq) == index + 1:
              # user wants to access the last sequence, return until end of data
!             return self.getField(field)[int(seq[index]):]
          if len(seq) < index + 1:
              # sequence index beyond number of sequences. raise exception
              raise IndexError('sequence does not exist.')
!         return self.getField(field)[int(seq[index]):int(seq[index + 1])]
  
      def getSequence(self, index):
          """Returns the sequence given by `index`.
--- 42,52 ----
          seq = ravel(self.getField('sequence_index'))
          if len(seq) == index + 1:
              # user wants to access the last sequence, return until end of data
!             return self.getField(field)[seq[index]:]
          if len(seq) < index + 1:
              # sequence index beyond number of sequences. raise exception
              raise IndexError('sequence does not exist.')
!         return self.getField(field)[seq[index]:seq[index + 1]]
  
      def getSequence(self, index):
          """Returns the sequence given by `index`.

```
