### ISSUE TITLE
slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by mg64ve** [pybrain/pybrain#217]
I have just installed Linux Mint 18.1 and tried to run Evolino sine test. 
I am getting the following error:

```
# python superimposed_sine.py

=== Learning to extrapolate 5 superimposed sine waves ===

creating training data
creating test data
creating EvolinoNetwork
creating EvolinoTrainer
======================
====== NEXT RUN (0)====
======================
=== TRAINING
Traceback (most recent call last):
  File "superimposed_sine.py", line 92, in <module>
    trainer.trainEpochs( 1 )
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
    self.train(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/supervised/trainers/evolino.py", line 131, in train
    filter.apply(self._population)
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/supervised/evolino/filter.py", line 117, in apply
    fitness = self._evaluateNet(net, dataset, self.wtRatio)
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/supervised/evolino/filter.py", line 59, in _evaluateNet
    sequence = dataset.getSequence(i)[1]
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/datasets/sequential.py", line 56, in getSequence
    return [self._getSequenceField(index, l) for l in self.link]
  File "/usr/local/lib/python2.7/dist-packages/PyBrain-0.3.3-py2.7.egg/pybrain/datasets/sequential.py", line 45, in _getSequenceField
    return self.getField(field)[seq[index]:]
TypeError: slice indices must be integers or None or have an __index__ method

```

modules version:

```
PyBrain (0.3.3)
scipy (0.18.1)
Python 2.7.12

```

Do you have an idea why this is happening?
Thanks.
Cheers.

**Comment by vanschelven** [comment]
I'm also running into this problem, furthermore the following issue seems to be the same one: https://github.com/pybrain/pybrain/issues/219

@BestSonny you created a pull request, but then closed it without it having been merged. Could you elaborate on how you proceeded?

**Comment by vanschelven** [comment]
I think the root cause may actually be that pybrain does not work with numpy >= 1.12.0

In the [release notes](https://docs.scipy.org/doc/numpy-1.12.0/release.html#compatibility-notes
)

> DeprecationWarning to error
> * Indexing with floats raises IndexError, e.g., a[0, 0.0].

**Comment by florisdenhengst** [comment]
Can confirm that reverting to numpy 1.11.0 resolved this issue for me.
