### ISSUE TITLE
Unit test fail on ubuntu

### ISSUE THREAD

**Issue by gormih** [pybrain/pybrain#219]
user@lubuntu1604:~/src/pybrain/pybrain/tests$ lsb_release -r
Release:	16.04
user@lubuntu1604:~/src/pybrain/pybrain/tests$ python runtests.py 
WARNING Module pybrain.tests.unittests.tools.test_rlgluebridge is missing dependencies: rlglue
INFO Tests found: pybrain.tests.unittests.tools.test_ibp_leftordered
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/supervised
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/unsupervised
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/structure
INFO Tests found: pybrain.tests.unittests.datasets.test_datasets_datasets
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/optimization
INFO Tests found: pybrain.tests.unittests.auxiliary.test_pca
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/rl
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_backprop
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_evolino
INFO Tests found: pybrain.tests.unittests.supervised.trainers.test_rprop
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/supervised/knn
INFO Tests found: pybrain.tests.unittests.supervised.knn.lsh.test_minhash
INFO Tests found: pybrain.tests.unittests.supervised.knn.lsh.test_nearoptimal
INFO Tests found: pybrain.tests.unittests.structure.connections.test_shared_connections
INFO Tests found: pybrain.tests.unittests.structure.connections.test_subsampling_connection
INFO Tests found: pybrain.tests.unittests.structure.connections.test_sliced_connections
INFO No fast networks available: No module named arac.pybrainbridge
INFO Tests found: pybrain.tests.unittests.structure.networks.test_borderswipingnetwork
INFO Tests found: pybrain.tests.unittests.structure.networks.test_bidirectional_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_recurrent_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_sort
INFO Tests found: pybrain.tests.unittests.structure.networks.test_swiping_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_cyclic_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_nested_network
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_decomposition
INFO Tests found: pybrain.tests.unittests.structure.networks.test_network_forward_backward
INFO Tests found: pybrain.tests.unittests.structure.networks.test_no_gravity_network
INFO Tests found: pybrain.tests.unittests.structure.modules.test_simple_mdlstm
INFO Tests found: pybrain.tests.unittests.structure.modules.test_peephole_mdlstm
INFO Tests found: pybrain.tests.unittests.structure.modules.test_simple_lstm_network
INFO Tests found: pybrain.tests.unittests.structure.modules.test_peephole_lstm
INFO Tests found: pybrain.tests.unittests.structure.modules.test_samplelayer
INFO Tests found: pybrain.tests.unittests.structure.networks.custom.test_capturegame_network
INFO Tests found: pybrain.tests.unittests.structure.networks.custom.test_convolutional_nets
INFO Tests found: pybrain.tests.unittests.optimization.populationbased.test_pso_ring
INFO No tests found in /home/user/src/pybrain/pybrain/tests/unittests/rl/environments
INFO Tests found: pybrain.tests.unittests.rl.environments.twoplayergames.test_pente
INFO Tests found: pybrain.tests.unittests.rl.environments.twoplayergames.test_capture_game
...FF...../usr/local/lib/python2.7/dist-packages/pybrain/structure/networks/borderswiping.py:58: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if p != None:
..FF.......F.F.......
======================================================================
FAIL: test_evolino (pybrain.tests.unittests.supervised.trainers)
Doctest: pybrain.tests.unittests.supervised.trainers.test_evolino
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.supervised.trainers.test_evolino
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 0, in test_evolino

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 33, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    trainer.trainEpochs( 1 )
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_evolino[9]>", line 1, in <module>
        trainer.trainEpochs( 1 )
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/evolino.py", line 131, in train
        filter.apply(self._population)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/evolino/filter.py", line 117, in apply
        fitness = self._evaluateNet(net, dataset, self.wtRatio)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/evolino/filter.py", line 59, in _evaluateNet
        sequence = dataset.getSequence(i)[1]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 34, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    trainer.evaluation.max_fitness > -100
Expected:
    True
Got:
    False
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_evolino.py", line 38, in pybrain.tests.unittests.supervised.trainers.test_evolino
Failed example:
    net.extrapolate(sequence, len(sequence))[-1][0]>55
Expected:
    True
Got:
    False

======================================================================
FAIL: test_rprop (pybrain.tests.unittests.supervised.trainers)
Doctest: pybrain.tests.unittests.supervised.trainers.test_rprop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.supervised.trainers.test_rprop
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 0, in test_rprop

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 23, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    t.trainOnDataset(ds, 4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_rprop[12]>", line 1, in <module>
        t.trainOnDataset(ds, 4)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/trainer.py", line 30, in trainOnDataset
        self.trainEpochs(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 57, in train
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 28, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    abs(n.params[10:15] - array([ -0.53868206, -0.54185834,  0.26726394, -1.90008234, -1.12114946])).round(5)
Expected:
    array([ 0.,  0.,  0.,  0.,  0.])
Got:
    array([ 0.07526,  0.07613,  0.0253 ,  0.0132 ,  0.60377])
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 34, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    t.trainOnDataset(ds, 4)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.supervised.trainers.test_rprop[15]>", line 1, in <module>
        t.trainOnDataset(ds, 4)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/trainer.py", line 30, in trainOnDataset
        self.trainEpochs(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/trainer.py", line 37, in trainEpochs
        self.train(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/rprop.py", line 43, in train
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 45, in _getSequenceField
        return self.getField(field)[seq[index]:]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/supervised/trainers/test_rprop.py", line 39, in pybrain.tests.unittests.supervised.trainers.test_rprop
Failed example:
    abs(n.params[5:10] - array([ -0.19241111,  1.43404022,  0.23062397, -0.40105413,  0.62100109])).round(5)
Expected:
    array([ 0.,  0.,  0.,  0.,  0.])
Got:
    array([ 0.04173,  0.14517,  0.53681,  0.06842,  0.07844])

======================================================================
FAIL: test_recurrent_network (pybrain.tests.unittests.structure.networks)
Doctest: pybrain.tests.unittests.structure.networks.test_recurrent_network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.networks.test_recurrent_network
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/networks/test_recurrent_network.py", line 0, in test_recurrent_network

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/networks/test_recurrent_network.py", line 16, in pybrain.tests.unittests.structure.networks.test_recurrent_network
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.structure.networks.test_recurrent_network[3]>", line 1, in <module>
        gradientCheck(n)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
FAIL: test_nested_ffn_and_rnn (pybrain.tests.unittests.structure.networks)
Doctest: pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/networks/test_nested_ffn_and_rnn.py", line 0, in test_nested_ffn_and_rnn

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/networks/test_nested_ffn_and_rnn.py", line 41, in pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.structure.networks.test_nested_ffn_and_rnn[14]>", line 1, in <module>
        gradientCheck(n)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
FAIL: test_simple_mdlstm (pybrain.tests.unittests.structure.modules)
Doctest: pybrain.tests.unittests.structure.modules.test_simple_mdlstm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.modules.test_simple_mdlstm
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/modules/test_simple_mdlstm.py", line 0, in test_simple_mdlstm

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/modules/test_simple_mdlstm.py", line 17, in pybrain.tests.unittests.structure.modules.test_simple_mdlstm
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_mdlstm[3]>", line 1, in <module>
        gradientCheck(n)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method

======================================================================
FAIL: test_simple_lstm_network (pybrain.tests.unittests.structure.modules)
Doctest: pybrain.tests.unittests.structure.modules.test_simple_lstm_network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for pybrain.tests.unittests.structure.modules.test_simple_lstm_network
  File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 0, in test_simple_lstm_network

----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 17, in pybrain.tests.unittests.structure.modules.test_simple_lstm_network
Failed example:
    gradientCheck(n)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_lstm_network[3]>", line 1, in <module>
        gradientCheck(n)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method
----------------------------------------------------------------------
File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/unittests/structure/modules/test_simple_lstm_network.py", line 27, in pybrain.tests.unittests.structure.modules.test_simple_lstm_network
Failed example:
    gradientCheck(net)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest pybrain.tests.unittests.structure.modules.test_simple_lstm_network[10]>", line 1, in <module>
        gradientCheck(net)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/tests/helpers.py", line 53, in gradientCheck
        res = b._checkGradient(d, True)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/supervised/trainers/backprop.py", line 114, in _checkGradient
        for seq in self.ds._provideSequences():
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 173, in _provideSequences
        return iter(map(list, iter(self)))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 169, in __iter__
        yield self.getSequenceIterator(i)
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 63, in getSequenceIterator
        return zip(*self.getSequence(index))
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 56, in getSequence
        return [self._getSequenceField(index, l) for l in self.link]
      File "/usr/local/lib/python2.7/dist-packages/pybrain/datasets/sequential.py", line 49, in _getSequenceField
        return self.getField(field)[seq[index]:seq[index + 1]]
    TypeError: slice indices must be integers or None or have an __index__ method

----------------------------------------------------------------------
Ran 31 tests in 12.422s

FAILED (failures=6)

**Comment by Dathiou** [comment]
I am having the same error as well. Let me know if you were able to fix it.

**Comment by EspenRemman** [comment]
same problem on ubuntu 16.04 lts virtualbox

**Comment by jdtsillas** [comment]
I am also seeing 6 failures on Windows. I used pip to install the dependencies (including scipy 1.0.0) and I had to change the use of expm2 to expm.
