### ISSUE TITLE
KohonenMap - SOM - NetworkWriter not working

### ISSUE THREAD

**Issue by tomymehdi** [pybrain/pybrain#233]
Hello,

I'm trying to save the KohonenMap result after a long training and getting the following error:
```

Traceback (most recent call last):
  File "kohonen.py", line 156, in <module>
    NetworkWriter.writeToFile(som, 'kohonen.xml')
  File "/Library/Python/2.7/site-packages/PyBrain-0.3-py2.7.egg/pybrain/tools/xml/networkwriter.py", line 30, in writeToFile
    w.writeNetwork(net, netroot)
  File "/Library/Python/2.7/site-packages/PyBrain-0.3-py2.7.egg/pybrain/tools/xml/networkwriter.py", line 43, in writeNetwork
    for im in net.inmodules:
AttributeError: 'KohonenMap' object has no attribute 'inmodules'
```

Is there something I'm missing about saving the KohonenMap?

**Comment by tomymehdi** [comment]
For those having problems with this i found an alternative.

I was trying the following (The error is the one on the issue):
```

from pybrain.structure.modules import KohonenMap
from pybrain.tools.xml.networkwriter import NetworkWriter
from pybrain.tools.xml.networkreader import NetworkReader
som = KohonenMap(11, 5)
NetworkWriter.writeToFile(som, 'kohonen.xml')
som_from_xml = NetworkReader('kohonen.xml')
print som.activate([1,2,3,4,5,6,7,8,9,10,11])
print som_from_xml.activate([1,2,3,4,5,6,7,8,9,10,11])
```

The alternative i found is the following:

```

import pickle
from pybrain.structure.modules import KohonenMap
som = KohonenMap(11, 5)
fileObject = open('kohonen.pickle', 'w')
pickle.dump(som, fileObject)
fileObject.close()
fileObject = open('kohonen.pickle','r')
som_from_pickle = pickle.load(fileObject)
print som.activate([1,2,3,4,5,6,7,8,9,10,11])
print som_from_pickle.activate([1,2,3,4,5,6,7,8,9,10,11])
```
