### ISSUE TITLE
LoggingAgent throws ValueError

### ISSUE THREAD

**Issue by benjaminalt** [pybrain/pybrain#234]
In the assertions in pybrain/rl/agents/logging.py in the getAction() method throw a ValueError if the state space is represented as a numpy array (or any array with more than one element):

```
Traceback (most recent call last):
  File "/media/data/Projects/hbp/hbpprak_locomotion/Nengo/main.py", line 32, in <module>
    main()
  File "/media/data/Projects/hbp/hbpprak_locomotion/Nengo/main.py", line 26, in main
    experiment.doInteractions(NUM_INTERACTIONS)
  File "/home/bal/Tools/nengo_rl/local/lib/python2.7/site-packages/pybrain/rl/experiments/experiment.py", line 18, in doInteractions
    self._oneInteraction()
  File "/home/bal/Tools/nengo_rl/local/lib/python2.7/site-packages/pybrain/rl/experiments/experiment.py", line 27, in _oneInteraction
    self.task.performAction(self.agent.getAction())
  File "/home/bal/Tools/nengo_rl/local/lib/python2.7/site-packages/pybrain/rl/agents/learning.py", line 48, in getAction
    LoggingAgent.getAction(self)
  File "/home/bal/Tools/nengo_rl/local/lib/python2.7/site-packages/pybrain/rl/agents/logging.py", line 42, in getAction
    assert self.lastobs != None
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The [documentation](https://github.com/pybrain/pybrain/blob/master/pybrain/rl/environments/environment.py) says that getSensors is supposed to return a numpy array of doubles, but the assertion failing tells me I made a programming mistake.

**Comment by drmargarido** [comment]
Try the fix I presented in the pull request #236 , should solve your problem.
