### ISSUE TITLE
No module named 'connections.__init__'; 'connections' is not a package

### ISSUE THREAD

**Issue by mechanikate** [pybrain/pybrain#241]
Using a Udemy tutorial, help?
Error:
`Traceback (most recent call last):
  File "C:\Users\matth\Desktop\tens.py", line 1, in <module>
    from pybrain.tools.shortcuts import buildNetwork
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pybrain\tools\shortcuts.py", line 7, in <module>
    from pybrain.structure.networks.feedforward import FeedForwardNetwork
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pybrain\structure\__init__.py", line 1, in <module>
    from connections.__init__ import *
ModuleNotFoundError: No module named 'connections.__init__'; 'connections' is not a package`
Code:
```from pybrain.tools.shortcuts import buildNetwork
from pybrain.datasets import SupervisedDataSet
from pybrain.supervised.trainers import BackpropTrainer

neuralNetwork = buildNetwork(2, 3, 1, bias=True)

dataset = SupervisedDataSet(2, 1)

#AND logicl relation
dataset.addSample((0,0),(0))
dataset.addSample((1,0),(0))
dataset.addSample((0,1),(0))
dataset.addSample((1,1),(0))

trainer = BackpropTrainer(neuralNetwork, dataset= dataset, learningRate=0.01, momentum=0.06)

for i in range(10000):
    error = trainer.train()
    if i % 1000 == 0:
        print("Error in iteration ", i," is: ", error)
        print(neuralNetwork.activate([0,0]))
        print(neuralNetwork.activate([1,0]))
        print(neuralNetwork.activate([0,1]))
        print(neuralNetwork.activate([1,1]))

print("\nResults: ")
print(neuralNetwork.activate([0,0]))
print(neuralNetwork.activate([1,0]))
print(neuralNetwork.activate([0,1]))
print(neuralNetwork.activate([1,1]))
```

**Comment by mechanikate** [comment]
Fixed it, was using python3.
