### ISSUE TITLE
cannot import name 'random' from 'scipy'

### ISSUE THREAD

**Issue by noeldum** [pybrain/pybrain#255]
I am using scipy 1.9.1 and I get the traceback below when using the buildNetwork function.

`Traceback (most recent call last):
  File "/home/nono/Desktop/tmp/neural/./main.py", line 3, in <module>
    from pybrain.tools.shortcuts import buildNetwork
  File "/usr/local/lib/python3.10/dist-packages/PyBrain-0.3.3-py3.10.egg/pybrain/__init__.py", line 1, in <module>
    from pybrain.structure.__init__ import *
  File "/usr/local/lib/python3.10/dist-packages/PyBrain-0.3.3-py3.10.egg/pybrain/structure/__init__.py", line 2, in <module>
    from pybrain.structure.modules.__init__ import *
  File "/usr/local/lib/python3.10/dist-packages/PyBrain-0.3.3-py3.10.egg/pybrain/structure/modules/__init__.py", line 3, in <module>
    from pybrain.structure.modules.gaussianlayer import GaussianLayer
  File "/usr/local/lib/python3.10/dist-packages/PyBrain-0.3.3-py3.10.egg/pybrain/structure/modules/gaussianlayer.py", line 3, in <module>
    from scipy import random
ImportError: cannot import name 'random' from 'scipy' (/usr/local/lib/python3.10/dist-packages/scipy-1.9.1-py3.10-linux-x86_64.egg/scipy/__init__.py)
`
Looks like an old reference where things have changed in scipy and not updated in pybrain probably.

Is pybrain still maintained? The last release is from 2015.

**Comment by nacho00112** [comment]
This worked for me:

```python
import sys, numpy
sys.modules["scipy.random"] = numpy.random
import pybrain
``` 
I encapsulated this code on a file `pylearn.py` like this:

> pylearn.py
```python
import sys, numpy
sys.modules["scipy.random"] = numpy.random
import pybrain
sys.modules[__name__] = pybrain
```
so i can import from it like this:
> myproject.py
```python
from pylearn.tools.shortcuts import buildNetwork
mynetwork = buildNetwork(2, 3, 1)
print(mynetwork)
```

**Comment by nacho00112** [comment]
This fork \([MarcusGrum pybrain fork](https://github.com/MarcusGrum/pybrain)\) also solves the bug directly on the source code, so you can close the issue
